[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "senseable-backend"
version = "0.1.0"
description = "System for culturally aware, multisensory, and personalized text accessibility"
authors = [
    { name = "Sourabrata Mukherjee" },
    { name = "Hamna" },
    { name = "Arnab Paul Choudhury" },
    { name = "Kalika Bali" },
    { name = "Sunayana Sitaram" }
]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "numpy",
    "scipy",
    "pandas",
    "scikit-learn",
    "torch",
    "sentence-transformers",
    "transformers",
    "spacy",
    "nltk",
    "networkx",
    "pyyaml",
    "orjson",
    "httpx",
    "tqdm",
    "python-multipart",
    "jinja2",
    "loguru"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.setuptools.packages.find]
where = ["."]